Repository Projeto-grupo-05/projeto, pull requests merged in 2023-05, with the labels that each got.

#41 Validacao edição máquinas
  site/public/edicaoMaquina.html
Labels: CODE REVIEW, Front-end

#40 Pré cadastro máquina
  site/public/cadastro_maquina.html
  site/public/css/cadastro_maquina.css
  site/public/js/cadastroMaquina.js
  site/public/listagem_maquina.html
  site/src/controllers/maquinasController.js
  site/src/controllers/usuarioController.js
  site/src/models/usuarioModel.js
Labels: CODE REVIEW, Back-end, Front-end, Ajustes

#43 fix/cadastro-fix
  site/public/cadastroFunc.html
Labels: Back-end, Ajustes

#46 Cadastro NU default funfando
  site/public/cadastroEmpre.html
  site/src/controllers/medidaController.js
  site/src/models/medidaModel.js
  site/src/routes/medidas.js
Labels: CODE REVIEW

#45 Dash gerente niv urg
  site/public/css/dashboard.css
  site/public/dashboard.html
  site/src/controllers/medidaController.js
  site/src/models/medidaModel.js
  site/src/routes/medidas.js
Labels: CODE REVIEW

#44 Edição Nível de Urgência
  site/public/dashboard.html
  site/public/edicaoNivUrg.html
  site/src/controllers/medidaController.js
  site/src/models/medidaModel.js
  site/src/routes/medidas.js
Labels: CODE REVIEW, Back-end

#47 Tela incidentes
  site/public/avisosDeMaquinas.html
  site/public/css/avisosMaquinas.css
  site/public/css/global.css
  site/public/dashboard.html
  site/public/js/avisosMaquina.js
  site/public/listagem_maquina.html
  site/src/controllers/maquinasController.js
  site/src/models/maquinasModel.js
  site/src/routes/maquinas.js
Labels: CODE REVIEW, Back-end, Front-end

#49 Dash tela unitaria
  site/public/js/cadastroMaquina.js
  site/public/js/telaUnitaria.js
  site/public/telaUnitaria.html
  site/src/controllers/maquinasController.js
  site/src/models/maquinasModel.js
  site/src/routes/maquinas.js
Labels: Back-end

#52 Fixtelaunitaria
  site/public/js/telaUnitaria.js
  site/public/telaUnitaria.html
  site/src/models/maquinasModel.js
Labels: CODE REVIEW, Back-end, Ajustes

#51 Tela de incidentes
  site/public/avisosDeMaquinas.html
  site/public/css/avisosMaquinas.css
  site/public/css/global.css
  site/public/edicaoNivUrg.html
  site/public/js/avisosMaquina.js
  site/public/listagem_maquina.html
  site/src/controllers/maquinasController.js
  site/src/models/maquinasModel.js
  site/src/routes/maquinas.js
Labels: CODE REVIEW, Back-end, Front-end

#53 fix
  site/public/js/telaUnitaria.js
  site/src/controllers/maquinasController.js
  site/src/models/maquinasModel.js
Labels: Ajustes

#48 Fazendo a bomba do dash funcionar
  site/public.zip
  site/public/dashboard.html
  site/public/js/avisosMaquina.js
  site/public/js/dashboard.js
  site/src/controllers/medidaController.js
  site/src/models/medidaModel.js
  site/src/models/usuarioModel.js
  site/src/routes/medidas.js
Labels: CODE REVIEW

#54 Dasboard gerente - FRONT
  site/public/css/dashboard.css
  site/public/css/global.css
  site/public/dashboard.html
  site/public/js/avisosMaquina.js
  site/public/js/dashboard.js
  site/public/listagem_maquina.html
  site/public/telaUnitaria.html
Labels: Front-end
