Repository Projeto-grupo-05/projeto, pull requests merged in 2023-04, with the labels that each got.

#20 Fiz os ajustes da api para a tela de login e está funcionando
  site/public/login.html
  site/src/controllers/usuarioController.js
  site/src/models/usuarioModel.js
Labels: CODE REVIEW, Back-end

#23 Adição de campo de usuário e alocação de botão "Cadastrar"
  site/public/cadastro_maquina.html
  site/public/css/cadastro_maquina.css
  site/public/js/cadastroMaquina.js
  site/src/controllers/usuarioController.js
  site/src/models/usuarioModel.js
  site/src/routes/usuarios.js
Labels: Back-end, Front-end

#19 Cadastro de usuário
  site/public/cadastroFunc.html
  site/src/controllers/maquinaController.js
  site/src/controllers/usuarioController.js
  site/src/models/maquinaModel.js
  site/src/models/usuarioModel.js
  site/src/routes/maquinas.js
  site/src/routes/usuarios.js
Labels: CODE REVIEW, Back-end

#22 Tela Listagem Maquinas
  site/app.js
  site/public/cadastroFunc.html
  site/public/css/listagem_maquina.css
  site/public/edicaoMaquina.html
  site/public/listagem_maquina.html
  site/src/controllers/maquinasController.js
  site/src/models/maquinasModel.js
  site/src/routes/maquinas.js
Labels: CODE REVIEW, Back-end

#25 Routes Maquinas ajustado
  site/src/routes/maquinas.js
Labels: CODE REVIEW, Back-end

#21 Api cadastro empresa
  site/public/cadastroEmpre.html
  site/public/css/cadastroEmpre.css
  site/src/controllers/usuarioController.js
  site/src/models/usuarioModel.js
  site/src/routes/usuarios.js
Labels: CODE REVIEW, Back-end

#29 Tela de avisos de maquinas
  site/public/avisosDeMaquinas.html
  site/public/css/cadastro_maquina.css
  site/public/css/telaUnitaria.css
  site/public/js/avisosMaquina.js
  site/public/js/telaUnitaria.js
  site/public/telaUnitaria.html
  site/src/controllers/maquinasController.js
  site/src/models/maquinasModel.js
  site/src/routes/maquinas.js
Labels: CODE REVIEW, Back-end

#27 Tela unitaria maquinas
  site/public/telaUnitaria.html
Labels: CODE REVIEW, Back-end, Front-end

#32 Css dash gerante
  site/public/assets/icons/macbookBLUE.png
  site/public/assets/icons/macbookGREEN.png
  site/public/assets/icons/macbookRED.png
  site/public/css/dashboard.css
  site/public/dashboard.html
  site/public/js/dashboard.js
Labels: CODE REVIEW, Front-end

#31 Listagem de incidentes
  site/public/avisosDeMaquinas.html
  site/public/cadastro_maquina.html
  site/public/css/avisosMaquinas.css
  site/public/css/global.css
  site/public/css/menuLateral.css
  site/public/js/avisosMaquina.js
Labels: CODE REVIEW, Front-end

#33 Validacao login
  site/public/cadastroEmpre.html
  site/public/cadastroFunc.html
  site/public/js/continuacao.js
  site/public/js/regex.js
  site/public/login.html
  site/src/models/usuarioModel.js
Labels: Front-end, Ajustes

#36 Novo select tela de avisos
  site/src/models/maquinasModel.js
Labels: CODE REVIEW, Back-end, Ajustes

#28 Css Tela de Edição Máquina
  site/public/css/edicaoMaquina.css
  site/public/edicaoMaquina.html
Labels: CODE REVIEW, Front-end

#35 Css dash gerante
  site/public/css/dashboard.css
  site/public/dashboard.html
  site/public/js/dashboard.js
Labels: CODE REVIEW, Front-end

#34 Ajustes gerais front-end
  package.json
  site/public/avisosDeMaquinas.html
  site/public/cadastroFunc.html
  site/public/cadastroInterno.html
  site/public/cadastro_maquina.html
  site/public/css/avisosMaquinas.css
  site/public/css/cadastroFunc.css
  site/public/css/cadastro_maquina.css
  site/public/css/global.css
  site/public/css/listagem_maquina.css
  site/public/css/login.css
  site/public/css/menuLateral.css
  site/public/dashboard.html
  site/public/index.html
  site/public/js/avisosMaquina.js
  site/public/js/continuacao.js
  site/public/js/telaUnitaria.js
  site/public/listagem_maquina.html
  site/public/login.html
  site/public/telaUnitaria.html
  site/src/controllers/maquinasController.js
  site/src/controllers/usuarioController.js
  site/src/models/usuarioModel.js
Labels: Front em progresso

#37 Ajustes fk excluir maquina
  site/src/models/maquinasModel.js
Labels: CODE REVIEW, Ajustes
